//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TariffFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariffs
    {
        public int Id { get; set; }
        public int OperatorId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Minutes { get; set; }
        public int DataGB { get; set; }
        public int Sms { get; set; }
    
        public virtual Operators Operators { get; set; }
    }
}
